#ifndef _OGLSCENE2_H_
#define _OGLSCENE2_H_

#define MYICON 101
#define IDBITMAP_MOON_TEXTRURE 103
#define IDBITMAP_STARS_TEXTRURE 105
#define IDBITMAP_TEXTURE_GRASS 107

#define IDBITMAP_BRICKSWALLPAPER 108
#define IDBITMAP_WHITEWALLPAPER 109
#define IDBITMAP_ROOFWALLPAPER 110
#define IDBITMAP_HOME_DOORTEXTURE 112
#define IDBITMAP_HOME_WINDOWTEXTURE 113
#define IDBITMAP_HOME_BASEBRICKSTEXTURE 114
#define IDBITMAP_WOODTEXTURE 115
#define IDBITMAP_BOOKTEXTURE 116
#define IDBITMAP_GANESHWALLPAPER 117
#define IDBITMAP_RAMSITAWALLPAPER 118
#define IDBITMAP_TRUNK 119
#define IDBITMAP_WATER 120
#define IDBITMAP_CHOURANG_TEXTURE 121
#define IDBITMAP_BLANK_BOOK_PAGE 122
#define IDBITMAP_LEAF 123
#define IDBITMAP_BOOK_COVER 124

BOOL initializeSceneTwo(void);
void displaySceneTwo(void);
void updateSceneTwo(void);
void uninitializeSceneTwo(void);

#endif
