#ifndef _OGLSCENE3_H_
#define _OGLSCENE3_H_

#define IDBITMAP_MAHAL_BASE_YELLOW_CARPET 302
#define IDBITMAP_MAHAL_RED_DESIGNE_CARPET 303
#define IDBITMAP_MAHAL_RED_PLAN_CARPET 304
#define IDBITMAP_MAHAL_BLUE_CARPET_YAGYA 305
#define IDBITMAP_MAHAL_RED_CIRCLE_DESIGNE 306
#define IDBITMAP_MAHAL_BLUE_DESIGN 307
#define IDBITMAP_RANGOLI_ONE 308
#define IDBITMAP_RANGOLI_TWO 309
#define IDBITMAP_FACE 310
#define IDBITMAP_RED_CLOTH 311
#define IDBITMAP_SKIN 312
#define IDBITMAP_FACE_KING 313
#define IDBITMAP_FACE_QUEEN 314
#define IDBITMAP_ORG_CLOTH 315
#define IDBITMAP_FACE_HRUSHI 316

BOOL initializeSceneThree(void);
void displaySceneThree(void);
void updateSceneThree(void);

#endif
