#pragma once

#define MYICON 101

#define IDBITMAP_BRICKSWALLPAPER 105
#define IDBITMAP_WHITEWALLPAPER 106
#define IDBITMAP_ROOFWALLPAPER 107
#define IDBITMAP_HOME_DOORTEXTURE 108
#define IDBITMAP_HOME_WINDOWTEXTURE 109
