#pragma once

#define MYICON 101

#define IDBITMAP_KUNDALI 102

#define IDBITMAP_STONE 103

#define IDBITMAP_WIN_7 104
#define IDBITMAP_WIN_XP 106
#define IDBITMAP_INTERNET 107
#define IDBITMAP_LAMINATEDWOODENFLOORING 108
#define IDBITMAP_TILEWALLPAPER 109
#define IDBITMAP_WALLPAPER_OLIVEGREEN 110
#define IDBITMAP_WALLPAPER_WOODENTEXTUREDARK 112
#define IDBITMAP_WALLPAPER_WOODENTEXTURE_LIGHT 113
#define IDBITMAP_WALLPAPER_CEILING 114
#define IDBITMAP_WALLPAPER_DOOR 115
#define IDBITMAP_WALLPAPER_SKY 116
#define IDBITMAP_WALLPAPER_BUILDING_ONE 117
#define IDBITMAP_WALLPAPER_BUILDING_TWO 118
#define IDBITMAP_KEYBOARD_TEXTURE 119
#define IDBITMAP_INTERNET_CAFE 120
#define MYMUSIC 121
//---------------------------------------------
#define IDBITMAP_BASETILE 122
#define IDBITMAP_ROAD 123
